WebApp/Controllers/CountryController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Hosting;
using System.IO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using LogicaAplicacion.UseCases.UCEntities.Countries;
using LogicaNegocio.Entidades;
using LogicaNegocio.VO;
using LogicaNegocio.Excepciones;
using LogicaAplicacion.UseCases.Interfaces;

namespace WebApp.Controllers
{
    public class CountryController : Controller
    {
        private ICreate<Country> _ucCreateCountry;
        private IRead<Country> _ucReadCountry;
        private IReadFilterCountry<Country> _ucReadFilterCountry;
        private IUpdate<Country> _ucUpdateCountry;
        private IDelete<Country> _ucDeleteCountry;

        private IWebHostEnvironment _environment;

        public CountryController(ICreate<Country> ucCreateCountry,
            IRead<Country> ucReadCountries,
            IReadFilterCountry<Country> ucReadFilterCountry, 
            IDelete<Country> ucDeleteCountry,
            IUpdate<Country> ucUpdateCountry,
            IWebHostEnvironment environment)
        {
            _ucCreateCountry = ucCreateCountry;
            _ucReadCountry = ucReadCountries;
            _ucReadFilterCountry = ucReadFilterCountry;
            _ucUpdateCountry = ucUpdateCountry;
            _ucDeleteCountry = ucDeleteCountry;
            _environment = environment;
        }
        public IActionResult Index ()
        {
            return View(_ucReadCountry.ReadAll());
        }
        [HttpPost]
        public IActionResult Index (string region)
        {
            ViewBag.Message = "";
            try
            {
                return View(_ucReadFilterCountry.FindByRegion(region));
            }
            catch (Exception e)
            {
                ViewBag.Message = e.Message;
                return View(_ucReadCountry.ReadAll());
            } 
        }
        [HttpPost]
        public IActionResult FindByISO (string iso)
        {
            List<Country> countries = new List<Country>();
            try
            {
                countries.Add(_ucReadFilterCountry.FindByISO(iso));
                return View("Index", countries);
            } catch (Exception e)
            {
                ViewBag.Message = e.Message;
                return View("Index", _ucReadCountry.ReadAll());
            }
        }
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Country country, string name, string isoalpha, float gdp, int population, string region, IFormFile image)
        {
            ViewBag.Message = "";
            Country c = country;
            try
            {
                country.Name = new NameValue(name);
                country.IsoAlfa3 = new ISOAlfa3Value(isoalpha);
                country.GDP = new PositiveFloatValue (gdp);
                country.Population = new PositiveIntegerValue(population);
                country.Region = new RegionValue(region);
                country.Image = isoalpha + ".png";
                SaveFile(country, image);
                _ucCreateCountry.Create(country);
                return RedirectToAction("Index");

            }
            catch (DomainException e)
            {
                ViewBag.Message = e.Message;
            }
            return View(c);
        }
        [HttpGet]
        public IActionResult Delete (int id)
        {
            ViewBag.Message = "";
            Country country = _ucReadCountry.FindById(id);
            try
            {
                _ucDeleteCountry.Delete(country);
            } catch (DomainException de)
            {
                ViewBag.Message = de.Message;
            }
            return View("Index", _ucReadCountry.ReadAll());
        }

        [HttpGet]
        public IActionResult Update (int id)
        {
            Country country = _ucReadCountry.FindById(id);
            return View(country);
        }
        [HttpPost]
        public IActionResult Update (int Id, string Name, string IsoAlpha3, float GDP, int Population, string Region)
        {
            Country country = new Country (Name, IsoAlpha3, GDP, Population, Region);
            country.Id = Id;
            _ucUpdateCountry.Update(country);
            return RedirectToAction("Index");
        }

        public void SaveFile (Country country, IFormFile file)
        {
            string wwwrootPath = _environment.WebRootPath;
            string fileName = country.IsoAlfa3.Value + ".png";
            string filePath = Path.Combine(wwwrootPath, "img", "countries", fileName);
            try
            {
                using (FileStream f = new FileStream(filePath, FileMode.Create))
                {
                    file.CopyTo(f);
                }
                country.Image = fileName;
            } catch (Exception e)
            {
                throw new Exception("Something went wrong, please try again later.");
            }
        }
    }
}

WebApp/Views/Country/Create.cshtml
@model LogicaNegocio.Entidades.Country

@{
    ViewData["Title"] = "Agregar país";
}

<h1>Agregar un país</h1>

<h4>Paises</h4>
<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" name="name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IsoAlfa3" class="control-label"></label>
                <input asp-for="IsoAlfa3" name="isoalpha" class="form-control" />
                <span asp-validation-for="IsoAlfa3" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label for="image" class="control-label"></label>
                <input type="file" name="image" class="form-control" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GDP" class="control-label"></label>
                <input asp-for="GDP" name="gdp" type="number" class="form-control" />
                <span asp-validation-for="GDP" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Population" class="control-label"></label>
                <input asp-for="Population" name="population" type="number" class="form-control" />
                <span asp-validation-for="Population" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Region" class="control-label"></label>
                <input asp-for="Region" name="region" class="form-control" />
                <span asp-validation-for="Region" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
            <div>
                @ViewBag.Message
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Al listado de países.</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApp/Views/Country/CreatePais.cshtml
@model LogicaNegocio.Entidades.Country

@{
    ViewData["Title"] = "AgregarPais";
}

<h1>AgregarPais</h1>

<h4>Pais</h4>
<hr />

@ViewBag.Mensaje

<div class="row">
    <div class="col-md-4">
        <form asp-action="CreatePais">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" name="Nombre" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IsoAlfa3" class="control-label"></label>
                <input asp-for="IsoAlfa3" name="IsoAlfa3" class="form-control" />
                <span asp-validation-for="IsoAlfa3" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GDP" class="control-label"></label>
                <input asp-for="GDP" name="PBI" type="number" class="form-control" />
                <span asp-validation-for="GDP" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Population" class="control-label"></label>
                <input asp-for="Population" name="Poblacion" type="number" class="form-control" />
                <span asp-validation-for="Population" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Region" class="control-label"></label>
                <input asp-for="Region" name="Region" class="form-control" />
                <span asp-validation-for="Region" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApp/Views/Country/Index.cshtml
@model IEnumerable<LogicaNegocio.Entidades.Country>

@{
    ViewData["Title"] = "Países";
}

<h1>Listado de países.</h1>

<p>
    <a asp-action="Create">Agregar un país.</a>
</p>

<div>
    <form asp-controller="Country" asp-action="Index" method="post">
        <label for="region">Buscar por región</label>
        <input type="text" name="region" placeholder="Ingresa una región..." />
        <input type="submit" value="Buscar" />
    </form>
</div>

<div>
    <form asp-controller="Country" asp-action="FindByISO" method="post">
        <label for="iso">Buscar por código ISO Alpha 3</label>
        <input type="text" name="iso" placeholder="Ingresa un código ISO Alpha 3..." />
        <input type="submit" value="Buscar" />
    </form>
    <p>@ViewBag.Message</p>
</div>

<table class="table">
    <thead>
        <tr>
            <th>
                Imagen
            </th>
            <th>
                ID
            </th>
            <th>
                Nombre
            </th>
            <th>
                ISO Alpha
            </th>
            <th>
                Región
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                <img class="img-thumbnail" style="width: 128px;" src="~/img/countries/@item.Image" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name.Value)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsoAlfa3.Value)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Region.Value)
            </td>
            <td>
                @Html.ActionLink("Edit", "Update", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
        }
    </tbody>
</table>

WebApp/Views/Country/Update.cshtml
@model LogicaNegocio.Entidades.Country

@{
    ViewData["Title"] = "Editar";
}

<h1>Editar un país</h1>

<h4>Países.</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Update" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" readonly />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input name="Name" asp-for="Name.Value" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IsoAlfa3" class="control-label"></label>
                <input name="IsoAlpha3" asp-for="IsoAlfa3.Value" class="form-control" />
                <span asp-validation-for="IsoAlfa3" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GDP" class="control-label"></label>
                <input name="GDP" asp-for="GDP.Value" class="form-control" />
                <span asp-validation-for="GDP" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Population" class="control-label"></label>
                <input name="Populaton" asp-for="Population.Value" class="form-control" />
                <span asp-validation-for="Population" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Region" class="control-label"></label>
                <input name="Region" asp-for="Region.Value" class="form-control" />
                <span asp-validation-for="Region" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Al listado de países.</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}