WebApp/Controllers/NationalTeamController.cs
using LogicaAplicacion.UseCases.Interfaces;
using LogicaAplicacion.UseCases.UCEntities.Countries;
using LogicaNegocio.Entidades;
using LogicaNegocio.Excepciones;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApp.Mapper;
using WebApp.Models;

namespace WebApp.Controllers
{
    public class NationalTeamController : Controller
    {
        private ICreate<NationalTeam> _ucCreateNationalTeam;
        private IRead<NationalTeam> _ucReadNationalTeam;
        private IUpdate<NationalTeam> _ucUpdateNationalTeam;
        private IDelete<NationalTeam> _ucDeleteNationalTeam;
        private IRead<Country> _ucCountry;

        public NationalTeamController(
            ICreate<NationalTeam> createNT,
            IRead<NationalTeam> readNT,
            IUpdate<NationalTeam> updateNT,
            IDelete<NationalTeam> deleteNT,
            IRead<Country> ucCountry
            )
        {
            _ucCreateNationalTeam = createNT;
            _ucReadNationalTeam = readNT;
            _ucUpdateNationalTeam = updateNT;
            _ucDeleteNationalTeam = deleteNT;
            _ucCountry = ucCountry;
        }


        // GET: NationalTeamController
        public IActionResult Index(int Id)
        {
            try
            {
                return View(NationalTeamMapper.FromNationalTeams(_ucReadNationalTeam.ReadAll()));
            }
            catch (Exception e)
            {
                throw new Exception($"Error: {e.Message}");
            }
        }

        public IActionResult Details(int id)
        {
            try
            {
                return View(NationalTeamMapper.FromNationalTeam(_ucReadNationalTeam.FindById(id)));
            }
            catch(DomainException de)
            {
                throw new DomainException(de.Message); 
            }
            catch (Exception e)
            {
                throw new Exception(e.Message);
            }
        }
        
        public IActionResult Create()
        {
            ViewBag.CountriesList = _ucCountry.ReadAll();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(NationalTeamVM ntVM)
        {
            ViewBag.message = "";
            ViewBag.CountriesList = _ucCountry.ReadAll();
            try
            {
                NationalTeam nationalTeam = NationalTeamMapper.ToNationalTeam(ntVM);
                nationalTeam.Country = _ucCountry.FindById(ntVM.idCountry);
                _ucCreateNationalTeam.Create(nationalTeam);

                return RedirectToAction("Index");
            }
            catch (DomainException de)
            {
                ViewBag.message = de.Message;
            }
            catch (Exception e)
            {
                ViewBag.message = e.Message;
            }
            //prueba?
            return View(ntVM);
        }

        public IActionResult Edit(int id)
        {
            NationalTeam nt = _ucReadNationalTeam.FindById(id);
            NationalTeamVM ntVM = NationalTeamMapper.FromNationalTeam(nt);
            ntVM.idCountry = nt.Country.Id;

            ViewBag.NT = ntVM;
            
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(NationalTeamVM ntVM)
        {
            try
            {
                NationalTeam nt = NationalTeamMapper.ToNationalTeam(ntVM);
                nt.Country = _ucCountry.FindById(ntVM.idCountry);
                _ucUpdateNationalTeam.Update(nt);
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                return View();
            }
        }

        public IActionResult Delete(int id)
        {
            _ucDeleteNationalTeam.Delete(new NationalTeam() { Id = id });
            return RedirectToAction("Index");
        }
    }
}

WebApp/Views/NationalTeam/Create.cshtml
@model WebApp.Models.NationalTeamVM

@{ ViewData["Title"] = "Agregar selección nacional"; }

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

<h1>Agregar una selección nacional.</h1>

<h4>Selecciones nacionales.</h4>
<div>@ViewBag.message</div>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-controller="NationalTeam" asp-action="Create" method="POST">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="idCountry" class="control-label"></label>
                <select asp-for="idCountry" name="idCountry" class="form-control">
                    @foreach (var item in ViewBag.CountriesList)
                    {
                        <option value="@item.Id">@item.Name.Value</option>
                    }
                </select>
                <span asp-validation-for="idCountry" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Bettors" class="control-label"></label>
                <input asp-for="Bettors" class="form-control" />
                <span asp-validation-for="Bettors" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Al listado de selecciones nacionales.</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApp/Views/NationalTeam/Details.cshtml
@model WebApp.Models.NationalTeamVM

@{
    ViewData["Title"] = "Detalle de selección nacional";
}

<h1>Selecciones nacionales.</h1>

<div>
    <h4>Selección nacional.</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.idCountry)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.idCountry)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Phone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Bettors)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Bettors)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    <a asp-action="Index">Al listado de selecciones nacionales.</a>
</div>

WebApp/Views/NationalTeam/Edit.cshtml
@model WebApp.Models.NationalTeamVM

@{
    ViewData["Title"] = "Editar";
}

<h1>Selecciones nacionales.</h1>

<h4>Selección nacional.</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" method="POST">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" value="@ViewBag.NT.Id" readonly />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="idCountry" class="control-label"></label>
                <input asp-for="idCountry" class="form-control" value="@ViewBag.NT.idCountry" />
                <span asp-validation-for="idCountry" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" value="@ViewBag.NT.Name" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" value="@ViewBag.NT.Phone" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" value="@ViewBag.NT.Email" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Bettors" class="control-label"></label>
                <input asp-for="Bettors" class="form-control" value="@ViewBag.NT.Bettors" />
                <span asp-validation-for="Bettors" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Al listado de selecciones nacionales.</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApp/Views/NationalTeam/Index.cshtml
@model IEnumerable<NationalTeamVM>

@{
    ViewData["Title"] = "Listado de selecciones nacionales.";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Agregar una selección nacional.</a>
    <div>
        <form asp-action="Index" method="GET">
            <div>
                <label name="Id" class="control-label"></label>
                <input name="Id" class="form-control" />
                <span name="Id" class="text-danger"></span>
                <div class="form-group">
                    <input type="submit" value="Find" class="btn btn-primary" />
                </div>
            </div>

        </form>
    </div>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.idCountry)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Phone)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Bettors)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.idCountry)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Phone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Bettors)
            </td>
            @*<td>
            @item.idCountry
        </td>*@
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.Id}) |
                @Html.ActionLink("Details", "Details", new { id=item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.Id})
            </td>
        </tr>
}
    </tbody>
</table>